apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: dev
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: dep
    repoURL: https://github.com/ClownandBox/dev.git
    targetRevision: HEAD