apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: app
    repoURL: https://github.com/ClownandBox/dev.git
    targetRevision: HEAD