apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: dev 
spec:
  replicas: 1
    spec:
      containers:
      - name: dev
        image: ubuntu:latest
        command: ["sh", "-c", "sleep infinity"]